### ISSUE TITLE
Sever name

### ISSUE THREAD

**Issue by Yasser-A420** [TAEMBO/PC-Creator-bot#2]
just letting you know since the bot code is public you might have to change it so it dosent say they are on the PCC discord for the DM Forward thing and make it say the proper discord server name lol

**Comment by Yasser-A420** [comment]
![315864C7-D682-471A-832C-DC9F523101DF](https://user-images.githubusercontent.com/73202985/112677235-d99d9880-8e3f-11eb-902e-3885aff6f2ee.jpeg)

**Comment by AseCoder** [comment]
Bot was made to be only for pcc discord but will fix
